apiVersion: v1
imagePullSecrets:
- name: dockerhub
- name: tekton-pipeline-dockercfg-5mqvv
- name: pipeline-dockercfg-gdpz7
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-11-18T13:36:52Z"
  name: tekton-pipeline
  namespace: tekton-demo
  resourceVersion: "84393468"
  uid: 07e59330-5e7d-43d9-81ef-147cdcd1ee6d
secrets:
- name: dockerhub
- name: tekton-pipeline-dockercfg-5mqvv
- name: pipeline-dockercfg-gdpz7
